// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN01pVGbotIaZWgi59Hs3M9sh9_3lWjHo',
    appId: '1:38986827146:web:d0255909a3b7a06c163473',
    messagingSenderId: '38986827146',
    projectId: 'fyp-mobile-app-and-web-portal',
    authDomain: 'fyp-mobile-app-and-web-portal.firebaseapp.com',
    storageBucket: 'fyp-mobile-app-and-web-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiK_EhjjeS7IwA3QbKe85JvDjVYT43H_4',
    appId: '1:38986827146:android:b4c1ebff1ac628c9163473',
    messagingSenderId: '38986827146',
    projectId: 'fyp-mobile-app-and-web-portal',
    storageBucket: 'fyp-mobile-app-and-web-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpctGDN8Yy-B5ML1g_13Ga1sUX19yN88',
    appId: '1:38986827146:ios:01bd8e8f2fb5fbc9163473',
    messagingSenderId: '38986827146',
    projectId: 'fyp-mobile-app-and-web-portal',
    storageBucket: 'fyp-mobile-app-and-web-portal.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEpctGDN8Yy-B5ML1g_13Ga1sUX19yN88',
    appId: '1:38986827146:ios:01bd8e8f2fb5fbc9163473',
    messagingSenderId: '38986827146',
    projectId: 'fyp-mobile-app-and-web-portal',
    storageBucket: 'fyp-mobile-app-and-web-portal.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN01pVGbotIaZWgi59Hs3M9sh9_3lWjHo',
    appId: '1:38986827146:web:14ff3b828fa840d1163473',
    messagingSenderId: '38986827146',
    projectId: 'fyp-mobile-app-and-web-portal',
    authDomain: 'fyp-mobile-app-and-web-portal.firebaseapp.com',
    storageBucket: 'fyp-mobile-app-and-web-portal.firebasestorage.app',
  );
}
